# Astral Platform - AD/Kerberos (template SEM segredos)
astral.ad.enabled=true
astral.ad.spnego=false
astral.ad.domain=srvcloud.cloud
astral.ad.realm=SRVCLOUD.CLOUD
astral.ad.user=
astral.ad.pass=
astral.ad.keytab=/etc/astral/astral.keytab
astral.ad.spn=
astral.ad.fqdn=
