import OverviewGo from '../modules/overview/pages/Index';
import Firewall from '../modules/firewall/pages/Index';
import ProxyPage from '../modules/proxy/pages/Index';
import AdPage from '../modules/ad/pages/Index';
import PostgresPage from '../modules/postgres/pages/Index';
import ObsPage from '../modules/observabilidade/pages/Index';
import CompPage from '../modules/computacao/pages/Index';
import RedePage from '../modules/rede/pages/Index';
import TermPage from '../modules/terminal/pages/Index';
import CertsPage from '../modules/certs/pages/Index';
export const ORDER=['Visão geral','Firewall','Traffic Server','Active Directory','PostgreSQL','Observabilidade','Computação','Rede','Terminal','Certificados'];
export const ICONS={'Visão geral':'pi pi-home',Firewall:'pi pi-shield','Traffic Server':'pi pi-globe','Active Directory':'pi pi-sitemap',PostgreSQL:'pi pi-database',Observabilidade:'pi pi-chart-line',Computação:'pi pi-server',Rede:'pi pi-share-alt',Terminal:'pi pi-terminal',Certificados:'pi pi-key'};
export const PAGES={'Visão geral':OverviewGo,Firewall,'Traffic Server':ProxyPage,'Active Directory':AdPage,PostgreSQL:PostgresPage,Observabilidade:ObsPage,'Computação':CompPage,Rede:RedePage,Terminal:TermPage,Certificados:CertsPage};
