#!/usr/bin/env python3

import subprocess
import os
import sys
import time

class VLANConfigurator:
    def __init__(self):
        self.trunk_interface = "ens224"
        self.vlans = [
            ("10", "br-vlan10", "192.168.10.1/24"),
            ("2", "br-vlan2", "192.168.2.1/24"),
            ("20", "br-vlan20", "192.168.20.1/24"),
            ("30", "br-vlan30", "192.168.30.1/24")
        ]

    def run_command(self, cmd, shell=False, check=True):
        """Executa um comando e retorna o resultado"""
        try:
            if shell:
                result = subprocess.run(cmd, shell=True, check=check,
                                      capture_output=True, text=True)
            else:
                result = subprocess.run(cmd, check=check,
                                      capture_output=True, text=True)
            return result
        except subprocess.CalledProcessError as e:
            print(f"Erro ao executar comando: {cmd}")
            print(f"Erro: {e}")
            if check:
                raise
            return e

    def stop_pihole(self):
        """Para o serviço Pi-hole"""
        print("🛑 Parando Pi-hole...")
        self.run_command(["sudo", "systemctl", "stop", "pihole-FTL"], check=False)

    def cleanup_vlan_connections(self):
        """Limpa conexões de VLANs existentes"""
        print("🧹 Limpando conexões de VLANs existentes...")

        # Lista conexões atuais
        result = self.run_command(["nmcli", "-t", "-f", "NAME,DEVICE", "connection", "show"])

        # Encontra conexões de VLAN e bridges
        for line in result.stdout.split('\n'):
            if line and any(x in line for x in ['vlan', 'br-vlan']):
                connection_name = line.split(':')[0]
                print(f"  Removendo: {connection_name}")
                self.run_command(["sudo", "nmcli", "connection", "delete", connection_name], check=False)

    def configure_trunk(self):
        """Configura a interface trunk"""
        print(f"🔧 Configurando trunk {self.trunk_interface}...")

        # Verifica se já existe
        result = self.run_command(["nmcli", "connection", "show"], check=False)
        if f"{self.trunk_interface}-trunk" not in result.stdout:
            self.run_command([
                "sudo", "nmcli", "connection", "add", "type", "ethernet",
                "ifname", self.trunk_interface, "con-name", f"{self.trunk_interface}-trunk",
                "ipv4.method", "disabled", "ipv6.method", "disabled"
            ])
            print(f"  ✅ Trunk {self.trunk_interface} criado")
        else:
            print(f"  ℹ️ Trunk {self.trunk_interface} já existe")

    def create_vlans(self):
        """Cria bridges e VLANs"""
        print("🌐 Criando bridges e VLANs...")

        for vlan_id, bridge_name, ip_cidr in self.vlans:
            print(f"  📡 Criando VLAN {vlan_id} - {bridge_name}...")

            # Criar bridge
            self.run_command([
                "sudo", "nmcli", "connection", "add", "type", "bridge",
                "ifname", bridge_name, "con-name", f"bridge-vlan{vlan_id}",
                "ipv4.addresses", ip_cidr,
                "ipv4.method", "manual",
                "ipv6.method", "disabled",
                "bridge.stp", "no"
            ])

            # Criar VLAN e conectar à bridge
            self.run_command([
                "sudo", "nmcli", "connection", "add", "type", "vlan",
                "con-name", f"vlan{vlan_id}",
                "dev", self.trunk_interface,
                "id", vlan_id,
                "master", bridge_name,
                "slave-type", "bridge"
            ])

            print(f"  ✅ VLAN {vlan_id} configurada")

    def configure_pihole_toml(self):
        """Configura o arquivo pihole.toml corretamente"""
        print("⚙️ Configurando pihole.toml...")

        # Backup do arquivo original
        self.run_command(["sudo", "cp", "/etc/pihole/pihole.toml", "/etc/pihole/pihole.toml.backup"])

        # Conteúdo do pihole.toml
        toml_content = """# Pi-hole configuration file
# Generated by VLAN setup script

[dns]
interface = "br-lan"
listeningMode = "ALL"
upstreams = ["192.168.10.211", "1.1.1.1"]

[misc]
etc_dnsmasq_d = true

[dhcp]
active = true
start = "192.168.0.100"
end = "192.168.0.200"
router = "192.168.0.1"
leaseTime = "24h"
domain = "lan"
"""

        # Escreve o arquivo
        self.run_command(f"echo '{toml_content}' | sudo tee /etc/pihole/pihole.toml > /dev/null", shell=True)
        print("  ✅ pihole.toml configurado")

    def create_dnsmasq_configs(self):
        """Cria arquivos de configuração dnsmasq para cada VLAN"""
        print("📝 Criando configurações dnsmasq para VLANs...")

        configs = {
            "10-vlan10.conf": """
interface=br-vlan10
bind-interfaces
dhcp-range=192.168.10.100,192.168.10.200,255.255.255.0,24h
dhcp-option=3,192.168.10.1
dhcp-option=6,192.168.10.211,1.1.1.1
""",
            "20-vlan2.conf": """
interface=br-vlan2
bind-interfaces
dhcp-range=192.168.2.100,192.168.2.200,255.255.255.0,24h
dhcp-option=3,192.168.2.1
dhcp-option=6,192.168.10.211,1.1.1.1
""",
            "30-vlan20.conf": """
interface=br-vlan20
bind-interfaces
dhcp-range=192.168.20.100,192.168.20.200,255.255.255.0,24h
dhcp-option=3,192.168.20.1
dhcp-option=6,192.168.10.211,1.1.1.1
""",
            "40-vlan30.conf": """
interface=br-vlan30
bind-interfaces
dhcp-range=192.168.30.100,192.168.30.200,255.255.255.0,24h
dhcp-option=3,192.168.30.1
dhcp-option=6,192.168.10.211,1.1.1.1
"""
        }

        for filename, content in configs.items():
            filepath = f"/etc/dnsmasq.d/{filename}"
            self.run_command(f"echo '{content}' | sudo tee {filepath} > /dev/null", shell=True)
            print(f"  ✅ {filename} criado")

    def configure_iptables(self):
        """Configura iptables para DNS e DHCP - CORRIGIDO"""
        print("🔥 Configurando iptables...")

        # Interfaces que precisam de DNS e DHCP
        interfaces = ["br-lan", "br-vlan10", "br-vlan2", "br-vlan20", "br-vlan30"]

        for interface in interfaces:
            # DNS (UDP 53)
            self.run_command([
                "sudo", "iptables", "-A", "INPUT", "-i", interface,
                "-p", "udp", "--dport", "53", "-j", "ACCEPT"
            ], check=False)

            # DNS (TCP 53)
            self.run_command([
                "sudo", "iptables", "-A", "INPUT", "-i", interface,
                "-p", "tcp", "--dport", "53", "-j", "ACCEPT"
            ], check=False)

            # DHCP (UDP 67)
            self.run_command([
                "sudo", "iptables", "-A", "INPUT", "-i", interface,
                "-p", "udp", "--dport", "67", "-j", "ACCEPT"
            ], check=False)

            print(f"  ✅ Regras iptables para {interface}")

        print("  ✅ iptables configurado para DNS e DHCP")

    def activate_connections(self):
        """Ativa todas as conexões"""
        print("🔌 Ativando conexões...")

        # Ativar trunk
        self.run_command(["sudo", "nmcli", "connection", "up", f"{self.trunk_interface}-trunk"], check=False)

        # Ativar bridges e VLANs
        for vlan_id, bridge_name, ip_cidr in self.vlans:
            self.run_command(["sudo", "nmcli", "connection", "up", f"bridge-vlan{vlan_id}"])
            self.run_command(["sudo", "nmcli", "connection", "up", f"vlan{vlan_id}"])

        print("  ✅ Conexões ativadas")

    def restart_pihole(self):
        """Reinicia o Pi-hole"""
        print("🔄 Reiniciando Pi-hole...")
        self.run_command(["sudo", "systemctl", "restart", "pihole-FTL"])
        time.sleep(3)  # Aguarda inicialização
        print("  ✅ Pi-hole reiniciado")

    def verify_configuration(self):
        """Verifica a configuração final"""
        print("\n" + "="*50)
        print("✅ VERIFICAÇÃO FINAL")
        print("="*50)

        # 1. Interfaces de rede
        print("\n1. 📡 Interfaces de rede:")
        self.run_command("ip addr show | grep -E '(br-|vlan)' | grep -E '(inet|UP)'", shell=True, check=False)

        # 2. Conexões NM
        print("\n2. 🔗 Conexões NetworkManager:")
        self.run_command("nmcli connection show | grep -E '(bridge|vlan)'", shell=True, check=False)

        # 3. Arquivos dnsmasq.d
        print("\n3. 📁 Arquivos dnsmasq.d:")
        self.run_command("ls -la /etc/dnsmasq.d/", shell=True, check=False)

        # 4. Configuração TOML
        print("\n4. ⚙️ Configuração pihole.toml:")
        self.run_command("grep -E '(interface|listeningMode|etc_dnsmasq_d|active)' /etc/pihole/pihole.toml", shell=True, check=False)

        # 5. Status Pi-hole
        print("\n5. 🚦 Status Pi-hole:")
        self.run_command(["sudo", "systemctl", "status", "pihole-FTL", "--no-pager", "-l"], check=False)

        # 6. Porta 53
        print("\n6. 🔒 Porta 53:")
        self.run_command("sudo netstat -tulpn | grep :53", shell=True, check=False)

        # 7. iptables
        print("\n7. 🛡️ Regras iptables:")
        self.run_command("sudo iptables -L INPUT -n | grep -E '(53|67)'", shell=True, check=False)

    def run(self):
        """Executa todo o processo de configuração"""
        try:
            print("🚀 INICIANDO CONFIGURAÇÃO DE VLANS + PI-HOLE")
            print("="*50)

            # Executar passos na ordem
            steps = [
                self.stop_pihole,
                self.cleanup_vlan_connections,
                self.configure_trunk,
                self.create_vlans,
                self.configure_pihole_toml,
                self.create_dnsmasq_configs,
                self.configure_iptables,
                self.activate_connections,
                self.restart_pihole,
                self.verify_configuration
            ]

            for step in steps:
                step()

            # Resumo final
            print("\n" + "="*50)
            print("🎉 CONFIGURAÇÃO CONCLUÍDA COM SUCESSO!")
            print("="*50)
            print("\n📊 RESUMO DA CONFIGURAÇÃO:")
            print("  • LAN: 192.168.0.1/24 (via pihole.toml)")
            for vlan_id, bridge_name, ip_cidr in self.vlans:
                print(f"  • VLAN{vlan_id}: {ip_cidr} (via dnsmasq.d)")
            print("  • iptables configurado para DNS (53) e DHCP (67)")
            print("  • Pi-hole ouvindo em todas as interfaces")
            print("\n✅ Pronto para uso!")

        except Exception as e:
            print(f"\n❌ ERRO durante a configuração: {e}")
            sys.exit(1)

def main():
    """Função principal"""
    # Verifica se é root
    if os.geteuid() != 0:
        print("❌ Este script precisa ser executado como root/sudo")
        sys.exit(1)

    configurator = VLANConfigurator()
    configurator.run()

if __name__ == "__main__":
    main()
