import React,{useEffect,useState}from'react';
import{Button}from'primereact/button';import{Card}from'primereact/card';import{InputText}from'primereact/inputtext';import{Password}from'primereact/password';import{Tag}from'primereact/tag';import{ProgressSpinner}from'primereact/progressspinner';
import{api,login,me,logout}from'./services/api';
const nav=[['pi pi-home','Visão geral'],['pi pi-shield','Firewall'],['pi pi-globe','Traffic Server'],['pi pi-sitemap','Active Directory'],['pi pi-database','PostgreSQL'],['pi pi-chart-line','Observabilidade'],['pi pi-server','Computação'],['pi pi-share-alt','Rede'],['pi pi-terminal','Terminal']];
function Login({onAuth}){const[u,setU]=useState(''),[p,setP]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('');async function go(){setBusy(true);setErr('');try{onAuth(await login(u,p))}catch(e){setErr(e.message)}finally{setBusy(false)}}return <div className="login"><div className="login-card"><div className="brand">ASTRAL<small>Platform & HCI</small></div><p className="muted">Infraestrutura convergente, rede, segurança e computação.</p>{err&&<div className="error">{err}</div>}<span className="p-float-label"><InputText id="u" value={u} onChange={e=>setU(e.target.value)} onKeyDown={e=>e.key==='Enter'&&document.getElementById('p').focus()}/><label htmlFor="u">Usuário AD ou PostgreSQL</label></span><span className="p-float-label"><Password inputId="p" value={p} onChange={e=>setP(e.target.value)} feedback={false} toggleMask onKeyDown={e=>e.key==='Enter'&&go()}/><label htmlFor="p">Senha</label></span><Button label={busy?'Autenticando...':'Entrar'} icon="pi pi-sign-in" disabled={busy} onClick={go}/><small className="muted">AD Samba é tentado primeiro; PostgreSQL é fallback.</small></div></div>}
function App(){const[user,setUser]=useState(null),[loading,setLoading]=useState(true),[section,setSection]=useState('Visão geral');useEffect(()=>{me().then(setUser).catch(()=>{}).finally(()=>setLoading(false))},[]);if(loading)return <div className="center"><ProgressSpinner/></div>;if(!user)return <Login onAuth={setUser}/>;return <div className="shell"><aside><div className="brand">ASTRAL<small>Platform & HCI</small></div>{nav.map(([icon,name])=><button key={name} className={'nav '+(section===name?'active':'')} onClick={()=>setSection(name)}><i className={icon}/>{name}</button>)}<div className="spacer"/><Button text label={user.username} icon="pi pi-user"/><Button text label="Sair" icon="pi pi-sign-out" onClick={async()=>{await logout();setUser(null)}}/></aside><main><header><div><h1>{section}</h1><span className="muted">Spring MVC · Tomcat · PrimeReact</span></div><Tag value={(user.authorities||[]).some(a=>a.authority==='ROLE_ASTRAL_ADMIN')?'ADMIN':'USER'} severity="info"/></header>{section==='Visão geral'?<Dashboard/>:<Module title={section}/>}</main></div>}
function Dashboard(){const[fw,setFw]=useState(null);useEffect(()=>{api('/api/firewall/status').then(setFw).catch(()=>{})},[]);return <div className="grid"><Card title="Firewall"><div className="metric">{fw?.active?'ATIVO':'INTEGRADO'}</div><small className="muted">{fw?.rulesActive??'—'} regras</small></Card><Card title="Web"><div className="metric">Tomcat</div><small className="muted">Servlet stack, sem WebFlux/Thymeleaf.</small></Card><Card title="Identidade"><div className="metric">AD + PG</div><small className="muted">Samba AD e autenticação nativa PostgreSQL.</small></Card><Card title="Observabilidade"><div className="metric">Graylog</div><small className="muted">Mongo dedicado para metadados do Graylog.</small></Card></div>}
function Module({title}){return <Card title={title}><p className="muted">O shell foi separado da implementação dos módulos. As interfaces legadas continuam internas para não perder funções existentes enquanto cada módulo é migrado.</p><Tag value="Em integração" severity="warning"/></Card>}
export default App;
