-- =====================================================================
-- V100__acl_observabilidade_retencao.sql
--
-- POR QUE V100: a V1 declara que ela e' o baseline e que a proxima versao
-- comeca em 100. Numeracao com buraco de proposito: um dia, quando um
-- desenvolvedor abrir o flyway_schema_history e vir 1, 100, 200, ele sabe de
-- cara que houve um salto intencional (migracao fora do fluxo normal) do que
-- se fosse 1, 2, 3 e a diferenca fosse invisivel.
--
-- O QUE ESTE ARQUIVO CRIA
--   1) ACL -- as 4 tabelas do motor de navegacao (Task 3).
--   2) reconciliation -- a trilha de intencoes do motor (Task 2).
--   3) metric_* -- as 4 fontes de observacao que viram hypertable do
--      TimescaleDB (Task 5): CPU, memoria, disco e rede.
--
-- POR QUE AS HYPERTABLES NAO ESTAO AQUI
--   create_hypertable e add_retention_policy exigem a extensao carregada e
--   permissao de dono/superusuario. O Flyway roda como o usuario 'astral' do
--   /etc/astral/astral.env, que nao e' superusuario -- entao a extensao nao
--   pode ser criada dentro da migracao e a migration falharia na primeira
--   subida. A conversao para hypertable e a politica de 30 dias ficam em
--   scripts/configure-timescaledb.sh, executado como postgres, idempotente,
--   que tambem e' quem chama drop_chunks manualmente se precisar.
--   Este arquivo cria as tabelas COMUNS; a converte quem tem permissao.
--
-- NOMES DE COLUNA
--   Os nomes estao em snake_case porque e' o que o PhysicalNamingStrategy do
--   Spring faz com os atributos Java (createdAt -> created_at). Escrever em
--   camelCase aqui so funcionaria se o Hibernate e o SQL discordassem -- e a
--   divergencia so apareceria no ddl-auto=validate, tarde demais.
--
-- Idempotente: tudo IF NOT EXISTS. Rodar duas vezes nao quebra nada.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) ACL (Task 3)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.acl_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(64) NOT NULL,
    name character varying(128) NOT NULL,
    description character varying(512),
    -- true = negado por padrao para quem nao tem regra. E' a coluna que
    -- materializa "fechado por padrao" para a politica BY_CATEGORY.
    blocked_by_default boolean NOT NULL,
    source character varying(32) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT pk_acl_category PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_acl_category_code ON public.acl_category (code);

CREATE TABLE IF NOT EXISTS public.acl_domain (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    pattern character varying(255) NOT NULL,
    category_id bigint NOT NULL,
    source character varying(32) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT pk_acl_domain PRIMARY KEY (id),
    CONSTRAINT fk_acl_domain_category FOREIGN KEY (category_id)
        REFERENCES public.acl_category (id) ON DELETE RESTRICT
);
-- Unica por padrao: dois padroes iguais fariam a ordem de leitura decidir
-- a categoria, e ordem de leitura nao e' politica.
CREATE UNIQUE INDEX IF NOT EXISTS ix_acl_domain_pattern ON public.acl_domain (pattern);

CREATE TABLE IF NOT EXISTS public.acl_domain_override (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    pattern character varying(255) NOT NULL,
    ad_group character varying(128),
    action character varying(16) NOT NULL,
    reason character varying(255),
    enabled boolean NOT NULL,
    created_by character varying(64),
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT pk_acl_domain_override PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_acl_override_pattern ON public.acl_domain_override (pattern);

CREATE TABLE IF NOT EXISTS public.acl_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    ad_group character varying(128) NOT NULL,
    action character varying(16) NOT NULL,
    priority integer NOT NULL,
    enabled boolean NOT NULL,
    justification character varying(255),
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT pk_acl_rule PRIMARY KEY (id),
    CONSTRAINT fk_acl_rule_category FOREIGN KEY (category_id)
        REFERENCES public.acl_category (id) ON DELETE RESTRICT,
    -- Duas regras para o mesmo par fariam o motor escolher por ordem de
    -- id, que e' ordem de insercao, nao intencao do operador.
    CONSTRAINT uq_acl_rule_cat_grupo UNIQUE (category_id, ad_group)
);
CREATE INDEX IF NOT EXISTS ix_acl_rule_enabled ON public.acl_rule (enabled);

-- ---------------------------------------------------------------------
-- 2) TRILHA DE RECONCILIACAO (Task 2)
--
-- A tabela guarda TAMBEM o payload e o diff: quando a plataforma fizer
-- rollback automatico, a pergunta do incidente e' "o que estava escrito
-- antes". Sem isto, rollback vira uma acao sem narrativa.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reconciliation_intent (
    id character varying(36) NOT NULL,
    module character varying(16) NOT NULL,
    type character varying(64) NOT NULL,
    payload text,
    status character varying(20) NOT NULL,
    requested_by character varying(128),
    applied boolean NOT NULL,
    diff_text text,
    error text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    finished_at timestamp without time zone,
    trail character varying(2048),
    CONSTRAINT pk_reconciliation_intent PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_intent_status ON public.reconciliation_intent (status);
CREATE INDEX IF NOT EXISTS ix_intent_created ON public.reconciliation_intent (created_at);

-- ---------------------------------------------------------------------
-- 3) OBSERVABILIDADE (Task 5) -- 4 tabelas de amostra
--
-- Formato comum: ts + host + o que foi medido. Todas viram hypertable com
-- chunk de 1 dia e ganham retencao de 30 dias no script de configuracao.
--
-- POR QUE 30 DIAS: e' o horizonte em que um pico de sexta-feira ainda e'
-- comparavel com o de sexta-feira seguinte. Alem disso, com ~5.760 linhas/dia
-- por serie, 30 dias e' ~173k linhas -- leve para Timescale, e o drop_chunks
-- garante que isso nao cresce para sempre, que e' como bancos de metrica
-- viram incidente de disco.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.metric_cpu (
    ts timestamp without time zone NOT NULL,
    host character varying(64) NOT NULL,
    cores integer,
    used_pct double precision,
    user_pct double precision,
    system_pct double precision,
    iowait_pct double precision,
    load1 double precision,
    load5 double precision,
    load15 double precision
);
CREATE INDEX IF NOT EXISTS ix_metric_cpu_host_ts ON public.metric_cpu (host, ts DESC);

CREATE TABLE IF NOT EXISTS public.metric_memory (
    ts timestamp without time zone NOT NULL,
    host character varying(64) NOT NULL,
    total_mb bigint,
    used_mb bigint,
    available_mb bigint,
    free_mb bigint,
    cached_mb bigint,
    buffers_mb bigint,
    swap_used_mb bigint,
    used_pct double precision
);
CREATE INDEX IF NOT EXISTS ix_metric_memory_host_ts ON public.metric_memory (host, ts DESC);

-- Contagens acumuladas viram taxas ANTES de gravar: o acumulado e' otimo para
-- o kernel, inutil para quem quer saber "quanto por segundo". Guardar o delta
-- aqui torna a serie comparavel entre amostras de intervalo diferente.
CREATE TABLE IF NOT EXISTS public.metric_io (
    ts timestamp without time zone NOT NULL,
    host character varying(64) NOT NULL,
    device character varying(32) NOT NULL,
    read_bps bigint,
    write_bps bigint,
    reads_per_s double precision,
    writes_per_s double precision,
    util_pct double precision
);
CREATE INDEX IF NOT EXISTS ix_metric_io_host_ts ON public.metric_io (host, ts DESC);

CREATE TABLE IF NOT EXISTS public.metric_network (
    ts timestamp without time zone NOT NULL,
    host character varying(64) NOT NULL,
    iface character varying(32) NOT NULL,
    rx_bps bigint,
    tx_bps bigint,
    rx_pps bigint,
    tx_pps bigint,
    rx_errors bigint,
    tx_errors bigint,
    rx_drops bigint,
    tx_drops bigint
);
CREATE INDEX IF NOT EXISTS ix_metric_network_host_ts ON public.metric_network (host, ts DESC);
